In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data=pd.read_csv(r"C:\Users\Ajay Mulgir\portfolio project\Portfolio\GUWAHATI\WEEK5\Train_Data.csv")
test_data=pd.read_csv(r"C:\Users\Ajay Mulgir\portfolio project\Portfolio\GUWAHATI\WEEK5\Test_Data.csv")
Sample_Submission=pd.read_csv(r"C:\Users\Ajay Mulgir\portfolio project\Portfolio\GUWAHATI\WEEK5\Sample_Submission.csv")

In [3]:
train_data.head()

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag,attack
0,0,tcp,netbios_dgm,REJ,0,0,0,0,0,0,...,0.06,0.06,0.00,0.00,0.00,0.0,1.00,1.0,21,neptune
1,0,tcp,smtp,SF,1239,400,0,0,0,0,...,0.45,0.04,0.00,0.00,0.11,0.0,0.02,0.0,18,normal
2,0,tcp,http,SF,222,945,0,0,0,0,...,1.00,0.00,0.02,0.03,0.00,0.0,0.00,0.0,21,normal
3,0,tcp,http,SF,235,1380,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,21,normal
4,0,tcp,uucp_path,REJ,0,0,0,0,0,0,...,0.01,0.08,0.00,0.00,0.00,0.0,1.00,1.0,19,neptune

In [4]:
test_data.head()

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsrvcount,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag
0,0,tcp,mtp,REJ,0,0,0,0,0,0,...,7,0.03,0.08,0.0,0.0,0.0,0.0,1.0,1.0,20
1,0,tcp,http,SF,199,1721,0,0,0,0,...,255,1.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,21
2,0,tcp,discard,S0,0,0,0,0,0,0,...,14,0.05,0.09,0.0,0.0,1.0,1.0,0.0,0.0,18
3,0,tcp,telnet,S0,0,0,0,0,0,0,...,2,0.01,0.09,0.0,0.0,1.0,1.0,0.0,0.0,18
4,0,tcp,exec,S0,0,0,0,0,0,0,...,16,0.06,0.06,0.0,0.0,1.0,1.0,0.0,0.0,20

In [5]:
Sample_Submission.head()

    attack
0   normal
1   normal
2   normal
3  neptune
4  neptune

In [6]:
train_data.head()

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag,attack
0,0,tcp,netbios_dgm,REJ,0,0,0,0,0,0,...,0.06,0.06,0.00,0.00,0.00,0.0,1.00,1.0,21,neptune
1,0,tcp,smtp,SF,1239,400,0,0,0,0,...,0.45,0.04,0.00,0.00,0.11,0.0,0.02,0.0,18,normal
2,0,tcp,http,SF,222,945,0,0,0,0,...,1.00,0.00,0.02,0.03,0.00,0.0,0.00,0.0,21,normal
3,0,tcp,http,SF,235,1380,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,21,normal
4,0,tcp,uucp_path,REJ,0,0,0,0,0,0,...,0.01,0.08,0.00,0.00,0.00,0.0,1.00,1.0,19,neptune

In [7]:
train_data.shape

(86845, 43)

In [8]:
train_data.describe()

,duration,srcbytes,dstbytes,land,wrongfragment,urgent,hot,numfailedlogins,loggedin,numcompromised,...,dsthostsrvcount,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag
count,86845.000000,8.684500e+04,8.684500e+04,86845.000000,86845.0,86845.000000,86845.000000,86845.000000,86845.000000,86845.000000,...,86845.000000,86845.000000,86845.000000,86845.000000,86845.000000,86845.000000,86845.000000,86845.000000,86845.000000,86845.000000
mean,104.166872,8.455707e+03,2.732095e+03,0.000046,0.0,0.000035,0.144971,0.000771,0.441142,0.320583,...,123.338269,0.526457,0.050186,0.075810,0.016246,0.324666,0.318934,0.092391,0.091045,20.060522
std,1038.273538,3.582141e+05,5.543041e+04,0.006787,0.0,0.007588,1.837958,0.037009,0.496527,27.993474,...,112.704010,0.447353,0.103323,0.208388,0.055271,0.464291,0.463506,0.282768,0.281452,1.421425
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000e+00,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,12.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000
50%,0.000000,4.600000e+01,4.400000e+01,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,77.000000,0.550000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000
75%,0.000000,2.720000e+02,7.680000e+02,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,...,255.000000,1.000000,0.070000,0.020000,0.010000,1.000000,1.000000,0.000000,0.000000,21.000000
max,40504.000000,8.958152e+07,7.028652e+06,1.000000,0.0,2.000000,77.000000,4.000000,1.000000,7479.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,21.000000

In [9]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86845 entries, 0 to 86844
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   duration                86845 non-null  int64
 1   protocoltype            86845 non-null  object
 2   service                 86845 non-null  object
 3   flag                    86845 non-null  object
 4   srcbytes                86845 non-null  int64
 5   dstbytes                86845 non-null  int64
 6   land                    86845 non-null  int64
 7   wrongfragment           86845 non-null  int64
 8   urgent                  86845 non-null  int64
 9   hot                     86845 non-null  int64
 10  numfailedlogins         86845 non-null  int64
 11  loggedin                86845 non-null  int64
 12  numcompromised          86845 non-null  int64
 13  rootshell               86845 non-null  int64
 14  suattempted             86845 non-null  int64
 15  numroot                 86845 non-null  int64
 16  numfilecreations        86845 non-null  int64
 17  numshells               86845 non-null  int64
 18  numaccessfiles          86845 non-null  int64
 19  numoutboundcmds         86845 non-null  int64
 20  ishostlogin             86845 non-null  int64
 21  isguestlogin            86845 non-null  int64
 22  count                   86845 non-null  int64
 23  srvcount                86845 non-null  int64
 24  serrorrate              86845 non-null  float64
 25  srvserrorrate           86845 non-null  float64
 26  rerrorrate              86845 non-null  float64
 27  srvrerrorrate           86845 non-null  float64
 28  samesrvrate             86845 non-null  float64
 29  diffsrvrate             86845 non-null  float64
 30  srvdiffhostrate         86845 non-null  float64
 31  dsthostcount            86845 non-null  int64
 32  dsthostsrvcount         86845 non-null  int64
 33  dsthostsamesrvrate      86845 non-null  float64
 34  dsthostdiffsrvrate      86845 non-null  float64
 35  dsthostsamesrcportrate  86845 non-null  float64
 36  dsthostsrvdiffhostrate  86845 non-null  float64
 37  dsthostserrorrate       86845 non-null  float64
 38  dsthostsrvserrorrate    86845 non-null  float64
 39  dsthostrerrorrate       86845 non-null  float64
 40  dsthostsrvrerrorrate    86845 non-null  float64
 41  lastflag                86845 non-null  int64
 42  attack                  86845 non-null  object
dtypes: float64(15), int64(24), object(4)
memory usage: 28.5+ MB

In [10]:
X=train_data.drop(['attack'],axis=1)

In [11]:
X.head()

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsrvcount,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag
0,0,tcp,netbios_dgm,REJ,0,0,0,0,0,0,...,15,0.06,0.06,0.00,0.00,0.00,0.0,1.00,1.0,21
1,0,tcp,smtp,SF,1239,400,0,0,0,0,...,116,0.45,0.04,0.00,0.00,0.11,0.0,0.02,0.0,18
2,0,tcp,http,SF,222,945,0,0,0,0,...,255,1.00,0.00,0.02,0.03,0.00,0.0,0.00,0.0,21
3,0,tcp,http,SF,235,1380,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,21
4,0,tcp,uucp_path,REJ,0,0,0,0,0,0,...,3,0.01,0.08,0.00,0.00,0.00,0.0,1.00,1.0,19

In [12]:
y=train_data['attack']

In [13]:
y

0        neptune
1         normal
2         normal
3         normal
4        neptune
          ...
86840     normal
86841     normal
86842     normal
86843     normal
86844     normal
Name: attack, Length: 86845, dtype: object

In [14]:
y.value_counts()

attack
normal     53847
neptune    32998
Name: count, dtype: int64

In [15]:
train_data['attack'].value_counts()

attack
normal     53847
neptune    32998
Name: count, dtype: int64

In [16]:
X.head()

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsrvcount,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag
0,0,tcp,netbios_dgm,REJ,0,0,0,0,0,0,...,15,0.06,0.06,0.00,0.00,0.00,0.0,1.00,1.0,21
1,0,tcp,smtp,SF,1239,400,0,0,0,0,...,116,0.45,0.04,0.00,0.00,0.11,0.0,0.02,0.0,18
2,0,tcp,http,SF,222,945,0,0,0,0,...,255,1.00,0.00,0.02,0.03,0.00,0.0,0.00,0.0,21
3,0,tcp,http,SF,235,1380,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,21
4,0,tcp,uucp_path,REJ,0,0,0,0,0,0,...,3,0.01,0.08,0.00,0.00,0.00,0.0,1.00,1.0,19

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86845 entries, 0 to 86844
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   duration                86845 non-null  int64
 1   protocoltype            86845 non-null  object
 2   service                 86845 non-null  object
 3   flag                    86845 non-null  object
 4   srcbytes                86845 non-null  int64
 5   dstbytes                86845 non-null  int64
 6   land                    86845 non-null  int64
 7   wrongfragment           86845 non-null  int64
 8   urgent                  86845 non-null  int64
 9   hot                     86845 non-null  int64
 10  numfailedlogins         86845 non-null  int64
 11  loggedin                86845 non-null  int64
 12  numcompromised          86845 non-null  int64
 13  rootshell               86845 non-null  int64
 14  suattempted             86845 non-null  int64
 15  numroot                 86845 non-null  int64
 16  numfilecreations        86845 non-null  int64
 17  numshells               86845 non-null  int64
 18  numaccessfiles          86845 non-null  int64
 19  numoutboundcmds         86845 non-null  int64
 20  ishostlogin             86845 non-null  int64
 21  isguestlogin            86845 non-null  int64
 22  count                   86845 non-null  int64
 23  srvcount                86845 non-null  int64
 24  serrorrate              86845 non-null  float64
 25  srvserrorrate           86845 non-null  float64
 26  rerrorrate              86845 non-null  float64
 27  srvrerrorrate           86845 non-null  float64
 28  samesrvrate             86845 non-null  float64
 29  diffsrvrate             86845 non-null  float64
 30  srvdiffhostrate         86845 non-null  float64
 31  dsthostcount            86845 non-null  int64
 32  dsthostsrvcount         86845 non-null  int64
 33  dsthostsamesrvrate      86845 non-null  float64
 34  dsthostdiffsrvrate      86845 non-null  float64
 35  dsthostsamesrcportrate  86845 non-null  float64
 36  dsthostsrvdiffhostrate  86845 non-null  float64
 37  dsthostserrorrate       86845 non-null  float64
 38  dsthostsrvserrorrate    86845 non-null  float64
 39  dsthostrerrorrate       86845 non-null  float64
 40  dsthostsrvrerrorrate    86845 non-null  float64
 41  lastflag                86845 non-null  int64
dtypes: float64(15), int64(24), object(3)
memory usage: 27.8+ MB

In [18]:
X['protocoltype'].value_counts()

protocoltype
tcp     75876
udp      9929
icmp     1040
Name: count, dtype: int64

In [19]:
X['service'].value_counts()

service
http        31505
private     12859
domain_u     7196
smtp         5806
ftp_data     4929
            ...
printer        46
urh_i           9
red_i           6
tim_i           4
tftp_u          3
Name: count, Length: 65, dtype: int64

In [20]:
X['flag'].value_counts()

flag
SF      50672
S0      27773
REJ      6721
RSTO     1127
S1        294
RSTR      106
S2        103
S3         38
OTH        10
SH          1
Name: count, dtype: int64

In [21]:
X.shape

(86845, 42)

In [22]:
from sklearn.preprocessing import LabelEncoder , StandardScaler

categorical_cols = ['protocoltype', 'service', 'flag']
label_encoders = {col: LabelEncoder() for col in categorical_cols}
for col in categorical_cols:
    train_data[col] = label_encoders[col].fit_transform(train_data[col])
    test_data[col] = label_encoders[col].transform(test_data[col])

In [23]:
train_data

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag,attack
0,0,1,33,1,0,0,0,0,0,0,...,0.06,0.06,0.00,0.00,0.00,0.00,1.00,1.00,21,neptune
1,0,1,49,8,1239,400,0,0,0,0,...,0.45,0.04,0.00,0.00,0.11,0.00,0.02,0.00,18,normal
2,0,1,22,8,222,945,0,0,0,0,...,1.00,0.00,0.02,0.03,0.00,0.00,0.00,0.00,21,normal
3,0,1,22,8,235,1380,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21,normal
4,0,1,62,1,0,0,0,0,0,0,...,0.01,0.08,0.00,0.00,0.00,0.00,1.00,1.00,19,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86840,0,1,22,8,216,674,0,0,0,0,...,1.00,0.00,0.01,0.03,0.01,0.01,0.00,0.00,21,normal
86841,0,1,22,8,368,1725,0,0,0,0,...,1.00,0.00,0.03,0.05,0.00,0.00,0.13,0.06,20,normal
86842,28,1,18,8,1483,4152,0,0,0,30,...,0.28,0.04,0.01,0.00,0.00,0.00,0.00,0.00,20,normal
86843,0,1,49,8,1679,385,0,0,0,0,...,0.16,0.08,0.00,0.00,0.69,0.00,0.01,0.00,18,normal
86844,11343,1,55,8,3396,16694,0,0,0,0,...,0.18,0.02,0.00,0.00,0.23,0.33,0.00,0.00,18,normal

In [24]:
train_data['protocoltype'].value_counts()

protocoltype
1    75876
2     9929
0     1040
Name: count, dtype: int64

In [25]:
train_data['service'].value_counts()

service
22    31505
44    12859
11     7196
49     5806
19     4929
      ...
43       46
59        9
45        6
57        4
56        3
Name: count, Length: 65, dtype: int64

In [26]:
train_data['flag'].value_counts()

flag
8    50672
4    27773
1     6721
2     1127
5      294
3      106
6      103
7       38
0       10
9        1
Name: count, dtype: int64

In [27]:
X=train_data.drop(['attack'],axis=1)
y=train_data['attack']
y=y.replace({'normal':0,'neptune':1})

In [28]:
X.head()

,duration,protocoltype,service,flag,srcbytes,dstbytes,land,wrongfragment,urgent,hot,...,dsthostsrvcount,dsthostsamesrvrate,dsthostdiffsrvrate,dsthostsamesrcportrate,dsthostsrvdiffhostrate,dsthostserrorrate,dsthostsrvserrorrate,dsthostrerrorrate,dsthostsrvrerrorrate,lastflag
0,0,1,33,1,0,0,0,0,0,0,...,15,0.06,0.06,0.00,0.00,0.00,0.0,1.00,1.0,21
1,0,1,49,8,1239,400,0,0,0,0,...,116,0.45,0.04,0.00,0.00,0.11,0.0,0.02,0.0,18
2,0,1,22,8,222,945,0,0,0,0,...,255,1.00,0.00,0.02,0.03,0.00,0.0,0.00,0.0,21
3,0,1,22,8,235,1380,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,21
4,0,1,62,1,0,0,0,0,0,0,...,3,0.01,0.08,0.00,0.00,0.00,0.0,1.00,1.0,19

In [29]:
y.head()

0    1
1    0
2    0
3    0
4    1
Name: attack, dtype: int64

In [30]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86845 entries, 0 to 86844
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   duration                86845 non-null  int64
 1   protocoltype            86845 non-null  int32
 2   service                 86845 non-null  int32
 3   flag                    86845 non-null  int32
 4   srcbytes                86845 non-null  int64
 5   dstbytes                86845 non-null  int64
 6   land                    86845 non-null  int64
 7   wrongfragment           86845 non-null  int64
 8   urgent                  86845 non-null  int64
 9   hot                     86845 non-null  int64
 10  numfailedlogins         86845 non-null  int64
 11  loggedin                86845 non-null  int64
 12  numcompromised          86845 non-null  int64
 13  rootshell               86845 non-null  int64
 14  suattempted             86845 non-null  int64
 15  numroot                 86845 non-null  int64
 16  numfilecreations        86845 non-null  int64
 17  numshells               86845 non-null  int64
 18  numaccessfiles          86845 non-null  int64
 19  numoutboundcmds         86845 non-null  int64
 20  ishostlogin             86845 non-null  int64
 21  isguestlogin            86845 non-null  int64
 22  count                   86845 non-null  int64
 23  srvcount                86845 non-null  int64
 24  serrorrate              86845 non-null  float64
 25  srvserrorrate           86845 non-null  float64
 26  rerrorrate              86845 non-null  float64
 27  srvrerrorrate           86845 non-null  float64
 28  samesrvrate             86845 non-null  float64
 29  diffsrvrate             86845 non-null  float64
 30  srvdiffhostrate         86845 non-null  float64
 31  dsthostcount            86845 non-null  int64
 32  dsthostsrvcount         86845 non-null  int64
 33  dsthostsamesrvrate      86845 non-null  float64
 34  dsthostdiffsrvrate      86845 non-null  float64
 35  dsthostsamesrcportrate  86845 non-null  float64
 36  dsthostsrvdiffhostrate  86845 non-null  float64
 37  dsthostserrorrate       86845 non-null  float64
 38  dsthostsrvserrorrate    86845 non-null  float64
 39  dsthostrerrorrate       86845 non-null  float64
 40  dsthostsrvrerrorrate    86845 non-null  float64
 41  lastflag                86845 non-null  int64
dtypes: float64(15), int32(3), int64(24)
memory usage: 26.8 MB

In [31]:
from sklearn.model_selection import train_test_split

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
test_data_scaled = scaler.transform(test_data)

In [32]:
X_scaled

array([[-0.10032758, -0.30074572,  0.30278717, ...,  3.20974994,
         3.22954213,  0.66094499],
       [-0.10032758, -0.30074572,  1.38396873, ..., -0.25601019,
        -0.32348435, -1.44962509],
       [-0.10032758, -0.30074572, -0.44052515, ..., -0.32673999,
        -0.32348435,  0.66094499],
       ...,
       [-0.07335958, -0.30074572, -0.71082054, ..., -0.32673999,
        -0.32348435, -0.04257837],
       [-0.10032758, -0.30074572,  1.38396873, ..., -0.29137509,
        -0.32348435, -1.44962509],
       [10.82460202, -0.30074572,  1.78941181, ..., -0.32673999,
        -0.32348435, -1.44962509]])

In [33]:
test_data_scaled

array([[-0.10032758, -0.30074572,  0.16763948, ...,  3.20974994,
         3.22954213, -0.04257837],
       [-0.10032758, -0.30074572, -0.44052515, ..., -0.32673999,
        -0.32348435,  0.66094499],
       [-0.10032758, -0.30074572, -1.31898517, ..., -0.32673999,
        -0.32348435, -1.44962509],
       ...,
       [-0.10032758, -0.30074572, -0.30537746, ..., -0.32673999,
        -0.32348435, -0.04257837],
       [-0.10032758, -0.30074572, -0.64324669, ..., -0.32673999,
        -0.32348435,  0.66094499],
       [-0.10032758, -0.30074572,  1.04609949, ..., -0.32673999,
        -0.32348435,  0.66094499]])

In [34]:
x_train,x_val,y_train,y_val = train_test_split(X_scaled,y,test_size=0.3,random_state=42)

In [35]:
x_train.size

2553222

In [36]:
y_train

78954    1
71202    0
49399    0
17271    1
65632    0
        ..
6265     0
54886    0
76820    1
860      0
15795    1
Name: attack, Length: 60791, dtype: int64

In [37]:
y_val

86586    1
29760    0
45563    1
6478     0
22782    0
        ..
15614    0
54541    0
80328    0
14670    1
7790     1
Name: attack, Length: 26054, dtype: int64

In [38]:
x_val

array([[-0.10032758, -0.30074572, -0.91354208, ..., -0.32673999,
        -0.32348435, -1.44962509],
       [-0.10032758, -0.30074572, -0.44052515, ..., -0.32673999,
        -0.32348435,  0.66094499],
       [-0.10032758, -0.30074572,  1.78941181, ..., -0.32673999,
        -0.32348435, -1.44962509],
       ...,
       [-0.10032758,  2.63752204,  1.04609949, ..., -0.32673999,
        -0.32348435, -2.15314845],
       [-0.10032758, -0.30074572,  1.04609949, ..., -0.32673999,
        -0.32348435,  0.66094499],
       [-0.10032758, -0.30074572,  2.1948549 , ..., -0.32673999,
        -0.32348435, -0.74610173]])

In [39]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000 , random_state=42)
log_reg.fit(x_train,y_train)
y_pred=log_reg.predict(x_val)

In [40]:
from sklearn.metrics import f1_score
f1_score(y_pred,y_val)

0.999848568976831

In [41]:
x_val

array([[-0.10032758, -0.30074572, -0.91354208, ..., -0.32673999,
        -0.32348435, -1.44962509],
       [-0.10032758, -0.30074572, -0.44052515, ..., -0.32673999,
        -0.32348435,  0.66094499],
       [-0.10032758, -0.30074572,  1.78941181, ..., -0.32673999,
        -0.32348435, -1.44962509],
       ...,
       [-0.10032758,  2.63752204,  1.04609949, ..., -0.32673999,
        -0.32348435, -2.15314845],
       [-0.10032758, -0.30074572,  1.04609949, ..., -0.32673999,
        -0.32348435,  0.66094499],
       [-0.10032758, -0.30074572,  2.1948549 , ..., -0.32673999,
        -0.32348435, -0.74610173]])

In [42]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train,y_train)
y_pred=decision_tree.predict(x_val)

In [43]:
from sklearn.metrics import f1_score
f1_score(y_pred,y_val)

0.9994952554007672

In [44]:
from sklearn.ensemble import RandomForestClassifier

random_clf=RandomForestClassifier(random_state=30)
random_clf.fit(x_train,y_train)
y_pred=random_clf.predict(x_val)

In [45]:
f1_score(y_pred,y_val)

0.9999495280876192

In [46]:
from sklearn.svm import SVC

svc=SVC(random_state=42)
svc.fit(x_train,y_train)

y_pred= svc.predict(x_val)

In [47]:
f1_score(y_pred,y_val)

0.9999495229922769

In [48]:
COUNTER =0
for i in y_pred:
    print(i)
    COUNTER=COUNTER+1
    if COUNTER == 5:
        break

1
0
1
0
0

In [49]:
y_val

86586    1
29760    0
45563    1
6478     0
22782    0
        ..
15614    0
54541    0
80328    0
14670    1
7790     1
Name: attack, Length: 26054, dtype: int64

In [50]:

y_final_submit = svc.predict(test_data_scaled)

In [51]:
y_final_submit

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [52]:

Sample_Submission

        attack
0       normal
1       normal
2       normal
3      neptune
4      neptune
...        ...
21707   normal
21708  neptune
21709   normal
21710   normal
21711   normal

[21712 rows x 1 columns]

In [53]:
final_sub=pd.DataFrame(y_final_submit,columns=['attack'])

In [54]:
final_sub

       attack
0           1
1           0
2           1
3           1
4           1
...       ...
21707       0
21708       0
21709       1
21710       0
21711       1

[21712 rows x 1 columns]

In [55]:
final_sub.to_csv(r"C:\Users\Ajay Mulgir\portfolio project\Portfolio\GUWAHATI\WEEK5\week5_submission.csv")